### ISSUE TITLE
Add config option for redirect target (other than /panel)

### ISSUE THREAD

**Issue by pReya** [thathoff/kirby-oauth#24]
I know, this plugin is currently meant to log in Oauth users into the Kirby panel. However, Kirby users can also be used to implement restricted pages (see https://getkirby.com/docs/cookbook/security/access-restriction) by creating a user group, that don't has access to the panel.

Therefore, it'd be great, if there was an optional config option for a redirect target (after succesful login) other than `/panel`, so it could be used to direct the user to some restricted page, e.g. `/internalPage/someSubpage`.

Are you open this? I might come up with a PR, if this is okay for you.

**Comment by thathoff** [comment]
Sure, great Idea!

**Comment by sebastiangreger** [comment]
I believe this should already be achievable with Kirby 3.6 out-of-the-box (well, except for two bugs, https://github.com/getkirby/kirby/issues/4054 and https://github.com/getkirby/kirby/issues/4056, that need to be addressed first): by setting the [`home` option](https://getkirby.com/docs/reference/panel/blueprints/user#home-option) in a user blueprint, we can control where a user lands after login. This is extremely flexible, including custom site methods.

The neat thing is that the URL `/panel` also redirects to that configured "home URL" after the initial login. Since the OAuth plugin specifically redirects to `/panel`, this should comprehensively cover above use case and likely not require any changes to this plugin?

**Comment by pReya** [comment]
@sebastiangreger Yes, that's what I figured out, too. I don't think there need to be any adjustments to this plugin. Thanks for your research and the bug tickets! Closing this issue, as this can be achieved with Kirby alone.

**Comment by thathoff** [comment]
Great, thanks guys! 👍

**Comment by pReya** [comment]
> I believe this should already be achievable with Kirby 3.6 out-of-the-box (well, except for two bugs, [getkirby/kirby#4054](https://github.com/getkirby/kirby/issues/4054) and [getkirby/kirby#4056](https://github.com/getkirby/kirby/issues/4056), that need to be addressed first): by setting the [`home` option](https://getkirby.com/docs/reference/panel/blueprints/user#home-option) in a user blueprint, we can control where a user lands after login. This is extremely flexible, including custom site methods.
> 
> The neat thing is that the URL `/panel` also redirects to that configured "home URL" after the initial login. Since the OAuth plugin specifically redirects to `/panel`, this should comprehensively cover above use case and likely not require any changes to this plugin?

@sebastiangreger I've submitted two PRs to fix both of the bugs you discovered. Hope the Kirby team agrees with my fixes and we can get this merged in the next release.
